-- Create user_profiles table
CREATE TABLE public.user_profiles (
  id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  full_name text,
  avatar_url text,
  billing_address text,
  updated_at timestamptz DEFAULT now(),
  PRIMARY KEY (id)
);
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.user_profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.user_profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.user_profiles FOR UPDATE USING (auth.uid() = id);

-- Create properties table
CREATE TABLE public.properties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.user_profiles,
  name text NOT NULL,
  address text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can create properties." ON public.properties FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Individuals can view their own properties." ON public.properties FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Individuals can update their own properties." ON public.properties FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Individuals can delete their own properties." ON public.properties FOR DELETE USING (auth.uid() = user_id);

-- Create floors table
CREATE TABLE public.floors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id bigint REFERENCES public.properties ON DELETE CASCADE,
  floor_number integer NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.floors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can create floors." ON public.floors FOR INSERT WITH CHECK (auth.uid() = (SELECT user_id FROM public.properties WHERE id = property_id));
CREATE POLICY "Individuals can view their own floors." ON public.floors FOR SELECT USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = property_id));
CREATE POLICY "Individuals can update their own floors." ON public.floors FOR UPDATE USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = property_id));
CREATE POLICY "Individuals can delete their own floors." ON public.floors FOR DELETE USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = property_id));

-- Create units table
CREATE TABLE public.units (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floor_id bigint REFERENCES public.floors ON DELETE CASCADE,
  unit_number text NOT NULL,
  created_at timestamptz DEFAULT now()
);
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Individuals can create units." ON public.units FOR INSERT WITH CHECK (auth.uid() = (SELECT user_id FROM public.properties WHERE id = (SELECT property_id FROM public.floors WHERE id = floor_id)));
CREATE POLICY "Individuals can view their own units." ON public.units FOR SELECT USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = (SELECT property_id FROM public.floors WHERE id = floor_id)));
CREATE POLICY "Individuals can update their own units." ON public.units FOR UPDATE USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = (SELECT property_id FROM public.floors WHERE id = floor_id)));
CREATE POLICY "Individuals can delete their own units." ON public.units FOR DELETE USING (auth.uid() = (SELECT user_id FROM public.properties WHERE id = (SELECT property_id FROM public.floors WHERE id = floor_id)));
