-- Create payments table
CREATE TABLE public.payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES public.units ON DELETE CASCADE,
  amount numeric NOT NULL,
  payment_date date NOT NULL,
  status text DEFAULT 'due',
  created_at timestamptz DEFAULT now()
);

-- Create maintenance_requests table
CREATE TABLE public.maintenance_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES public.units ON DELETE CASCADE,
  description text NOT NULL,
  status text DEFAULT 'open',
  created_at timestamptz DEFAULT now()
);

-- Create electricity_readings table
CREATE TABLE public.electricity_readings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES public.units ON DELETE CASCADE,
  reading numeric NOT NULL,
  reading_date date NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Create notifications table
CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.user_profiles ON DELETE CASCADE,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Create room_history table
CREATE TABLE public.room_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id bigint REFERENCES public.units ON DELETE CASCADE,
  user_id uuid REFERENCES public.user_profiles ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date,
  created_at timestamptz DEFAULT now()
);

-- Create otp_verifications table
CREATE TABLE public.otp_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.user_profiles ON DELETE CASCADE,
  otp text NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now()
);
